### ISSUE TITLE
"Max number of formal params allowed per function" with default value throws an error

### ISSUE THREAD

**Issue by devconcept** [losingkeys/generator-jshint#6]
Pressing enter when prompted for the "Max number of formal params allowed per function" causes the script to stop with an error saying <<Object false has no method 'trim'>>

**Comment by sirLisko** [comment]
The code in this repository is fixed, the problem is that yeoman is not up to date.

**Comment by d0nkeyBOB** [comment]
I'm still getting the error after upgrading yo. Version 1.4.7. Running on a mac 10.10. Breaks after 'Max number of formal params allowed per function" 

    /Users/richarddoyle/.node/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
    TypeError: undefined is not a function

**Comment by tobsn** [comment]
? Max number of formal params allowed per function (number or false for no limit; default is false) (false)


readline.js:921
            throw err;
            ^

TypeError: input.trim is not a function
    at Object.prompts.validate (/Users/tobias/.nodebrew/node/v4.1.0/lib/node_modules/generator-jshint/app/index.js:167:25)
